Repository bitcoin-sv/spv-wallet-admin, pull requests merged in 2024-02, with the labels that each got.

#839 fix(BUX-578): not working build because of date-fns
  package.json
  src/App.jsx
  src/components/access-keys.js
  src/components/block-headers.js
  src/components/dashboard-sidebar.js
  src/components/dashboard/utxos-by-type.js
  src/components/destinations.js
  src/components/paymails.js
  src/components/transactions.js
  src/components/utxos.js
  src/components/xpubs.js
  src/pages/dashboard.js
  src/pages/login.jsx
  src/pages/transaction-new.jsx
  yarn.lock
Labels: bug-P3, bug-P1, work-in-progress, tested

#845 ci(BUX-582): add check for manual tests
  .github/workflows/on-pull-request.yml
Labels: work-in-progress

#866 feat(BUX-606): migrate box-console
  .all-contributorsrc
  .github/CODEOWNERS
  .github/FUNDING.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .goreleaser.yml
  LICENSE
  Makefile
  README.md
  package.json
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/config.default.json
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/manifest.json
  release/README.DOCKER.md
  src/components/block-headers.js
  src/components/dashboard-sidebar.js
  src/components/listing/admin.jsx
  src/components/paymails.js
  src/hooks/use-query-list.jsx
  src/hooks/user.js
  src/logger/index.js
  src/pages/access-keys.jsx
  src/pages/admin-login.jsx
  src/pages/admin/block-headers.jsx
  src/pages/admin/register-xpub.jsx
  src/pages/admin/transaction-record.jsx
  src/pages/dashboard.js
  src/pages/destination-new.jsx
  src/pages/destination.jsx
  src/pages/login.jsx
  src/pages/transaction-new.jsx
  src/pages/transaction.jsx
  src/pages/xpub.jsx
  src/routes.js
  yarn.lock
Labels: feature, tested
