Repository bitcoin-sv/spv-wallet-admin, pull requests merged in 2024-10, with the labels that each got.

#1036 feat(SPV-1005): added loading state, improved loading logic
  src/components/AddAccessKeyDialog/AddAccessKeyDialog.tsx
  src/components/AddPaymailDialog/AddPaymailDialog.tsx
  src/components/AddXpubDialog/AddXpubDialog.tsx
  src/components/ContactAcceptDialog/ContactAcceptDialog.tsx
  src/components/ContactDeleteDialog/ContactDeleteDialog.tsx
  src/components/ContactEditDialog/ContactEditDialog.tsx
  src/components/ContactRejectDialog/ContactRejectDialog.tsx
  src/components/DateRangeFilter/DateRangeFilter.tsx
  src/components/DestinationEditDialog/DestinationEditDialog.tsx
  src/components/LoadingSpinner/LoadingSpinner.tsx
  src/components/LoadingSpinner/index.ts
  src/components/PaymailDeleteDialog/PaymailDeleteDialog.tsx
  src/components/RevokeKeyDialog/RevokeKeyDialog.tsx
  src/components/TransactionEditDialog/TransactionEditDialog.tsx
  src/components/index.ts
Labels: tested

#1033 SPV-1010/WebhookView
  package.json
  src/components/AccessKeysTabContent/AccessKeysTabContent.tsx
  src/components/ContactsTabContent/ContactsTabContent.tsx
  src/components/DataTable/DataTable.tsx
  src/components/DestinationsTabContent/DestinationsTabContent.tsx
  src/components/PaymailsTabContent/PaymailsTabContent.tsx
  src/components/TransactionsTabContent/TransactionsTabContent.tsx
  src/components/UnsubscribeWebhook/UnsubscribeWebhook.tsx
  src/components/UnsubscribeWebhook/index.ts
  src/components/ViewDialog/ViewDialog.tsx
  src/components/WebhooksColumns/WebhooksColumns.tsx
  src/components/WebhooksTabContent/WebhooksTabContent.tsx
  src/components/WebhooksTabContent/index.ts
  src/components/XpubsTabContent/XpubsTabContent.tsx
  src/components/index.ts
  src/interfaces/webhook.ts
  src/routes/admin/_admin.tsx
  src/routes/admin/_admin.webhooks.tsx
  src/routes/routeTree.autogenerated.ts
  src/utils/index.ts
  src/utils/mapElements.ts
  src/utils/webhooksQueryOptions.tsx
  yarn.lock
Labels: feature, tested

#1040 chore(SPV-1000): add xpubs visual test
  playwright.config.ts
  src/__tests__/visual/_page-objects/login.pageobject.ts
  src/__tests__/visual/login-page.visual.test.ts
  src/__tests__/visual/login-page/__screenshoots__/login-page-login-form/login-page-login-form-1.png
  src/__tests__/visual/login-page/__screenshoots__/login-page-login-with-invalid-credentials/login-page-login-with-invalid-credentials-1.png
  src/__tests__/visual/login-page/login-page.visual.test.ts
  src/__tests__/visual/xpubs/__screenshoots__/xpubs-page-xpubs-table-with-data/xpubs-page-xpubs-table-with-data-1.png
  src/__tests__/visual/xpubs/xpubs-page.visual.test.ts
Labels: tested

#1037 feat(SPV-1096): Improved View layout
  package.json
  src/components/ViewDialog/ViewDialog.tsx
  yarn.lock
Labels: tested

#1038 feat(SPV-1097): Added refresh button
  src/components/ModeToggle/ModeToggle.tsx
  src/routes/admin/_admin.tsx
Labels: feature, tested

#1045 fix: refresh button also for non-admin user
  src/components/PageRefreshButton/PageRefreshButton.tsx
  src/components/PageRefreshButton/index.ts
  src/routes/admin/_admin.tsx
  src/routes/user/_user.tsx
Labels: tested

#1042 feat(SPV-1118): fix long texts in confirmation boxes
  src/components/ContactAcceptDialog/ContactAcceptDialog.tsx
  src/components/ContactDeleteDialog/ContactDeleteDialog.tsx
  src/components/ContactRejectDialog/ContactRejectDialog.tsx
  src/components/PaymailDeleteDialog/PaymailDeleteDialog.tsx
  src/components/RevokeKeyDialog/RevokeKeyDialog.tsx
  src/components/UnsubscribeWebhook/UnsubscribeWebhook.tsx
Labels: bug-P3, tested

#1041 feat(SPV-1107): hide "delete" button for records that are already deleted
  src/components/ContactsTabContent/ContactsTabContent.tsx
  src/components/PaymailsTabContent/PaymailsTabContent.tsx
Labels: bug-P3, tested

#1047 feat(SPV-1135): confirmation prompt on page reloading;
  src/components/PageRefreshButton/PageRefreshButton.tsx
  src/routes/routeTree.autogenerated.ts
Labels: tested

#1048 fix(SPV-1136): webhooks view is hanging when notifications are disabled.
  src/components/CustomErrorComponent/CustomErrorComponent.tsx
  src/components/WebhookErrorComponent/WebhookErrorComponent.tsx
  src/components/WebhookErrorComponent/index.ts
  src/routes/admin/_admin.webhooks.tsx
  src/utils/webhooksQueryOptions.tsx
Labels: tested
