Repository bitcoin-sv/spv-wallet-admin, pull requests merged in 2024-08, with the labels that each got.

#975 chore(SPV-952): migrate to flat eslint config
  .eslintrc.cjs
  eslint.config.js
  package.json
  src/components/ContactAcceptDialog/ContactAcceptDialog.tsx
  src/components/ContactDeleteDialog/ContactDeleteDialog.tsx
  src/components/ContactEditDialog/ContactEditDialog.tsx
  src/components/ContactRejectDialog/ContactRejectDialog.tsx
  src/components/DataTable/DataTable.tsx
  src/components/DestinationEditDialog/DestinationEditDialog.tsx
  src/components/PaymailDeleteDialog/PaymailDeleteDialog.tsx
  src/components/RecordTxDialogAdmin/RecordTxDialogAdmin.tsx
  src/components/RevokeKeyDialog/RevokeKeyDialog.tsx
  src/components/TransactionEditDialog/TransactionEditDialog.tsx
  src/components/ViewDialog/ViewDialog.tsx
  src/components/ui/badge.tsx
  src/components/ui/button.tsx
  src/contexts/AuthContext.tsx
  src/contexts/SpvWalletContext.tsx
  src/contexts/ThemeProviderContext.tsx
  src/index.css
  src/logger/index.ts
  src/routes/admin/_admin.access-keys.tsx
  src/routes/admin/_admin.contacts.tsx
  src/routes/admin/_admin.destinations.tsx
  src/routes/admin/_admin.paymails.tsx
  src/routes/admin/_admin.transactions.tsx
  src/routes/admin/_admin.xpub.tsx
  src/routes/user/_user.access-keys.tsx
  tailwind.config.js
  yarn.lock
Labels: tested

#976 Spv 961/add prettier scripts
  package.json
  src/components/ui/accordion.tsx
  src/components/ui/avatar.tsx
  src/components/ui/badge.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/dialog.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/popover.tsx
  src/components/ui/radio-group.tsx
  src/components/ui/select.tsx
  src/components/ui/sheet.tsx
  src/components/ui/skeleton.tsx
  src/components/ui/sonner.tsx
  src/components/ui/tabs.tsx
  src/components/ui/textarea.tsx
  src/components/ui/tooltip.tsx
  src/contexts/ThemeProviderContext.tsx
  src/contexts/index.ts
  src/index.css
  src/lib/utils.ts
  src/main.tsx
  src/routes/about.lazy.tsx
  src/routes/routeTree.autogenerated.ts
Labels: chore, tested

#977 chore(SPV-966): remove goreleaser + makefile
  .goreleaser.yml
  .make/common.mk
  Makefile
  README.md
Labels: chore, tested

#980 feat(SPV-974) remove utxos item in admin menu
  src/routes/admin/_admin.tsx
Labels: tested

#972 fix(SPV-954): Server URL field constantly changes from undefined to http://
  src/hooks/useServerUrl.tsx
Labels: tested

#981 feat(SPV-977) remove utxos item in user menu
  src/routes/user/_user.tsx
Labels: tested

#983 feat(SPV-978) remove "contacts" menu item from user view
  src/routes/user/_user.tsx
Labels: feature, tested

#982 feat(SPV-977) "search by..." label changed to "search"
  src/components/Searchbar/Searchbar.tsx
Labels: feature, tested

#979 ci(SPV-962): add Github Actions workflow for feature branches
  .github/workflows/on-push.yml
  package.json
Labels: tested

#990 fix(SPV-976): user transactions shown on init
  src/routes/user/_user.transactions.tsx
Labels: tested

#991 feat(SPV-987): remove tabs section from user transactions
  src/routes/user/_user.transactions.tsx
Labels: tested

#992 fix(SPV-973): admin transactions shown on init
  src/routes/admin/_admin.transactions.tsx
Labels: tested

#993 feat(SPV-989): hide "record transaction" button for admin
  src/components/TransactionsTabContent/TransactionsTabContent.tsx
  src/routes/admin/_admin.transactions.tsx
Labels: tested

#998 fix(SPV-990): stringify "outputs" field in view dialog
  src/components/ViewDialog/ViewDialog.tsx
Labels: tested

#995 feat(SPV-959): Fixed react-refresh plugin warnings, moved files.
  src/components/AccessKeysColumns/AccessKeysColumns.tsx
  src/components/AddPaymailDialog/AddPaymailDialog.tsx
  src/components/AddXpubDialog/AddXpubDialog.tsx
  src/components/ContactAcceptDialog/ContactAcceptDialog.tsx
  src/components/ContactDeleteDialog/ContactDeleteDialog.tsx
  src/components/DataTable/DataTable.tsx
  src/components/DataTable/DataTablePagination.tsx
  src/components/DateRangeFilter/DateRangeFilter.tsx
  src/components/DestinationsColumns/DestinationsColumns.tsx
  src/components/ModeToggle/ModeToggle.tsx
  src/components/PaymailsColumns/PaymailColumns.tsx
  src/components/Profile/Profile.tsx
  src/components/RecordTxDialogAdmin/RecordTxDialogAdmin.tsx
  src/components/RecordTxDialogUser/PrepareTxDialogUser.tsx
  src/components/TransactionsColumns/columns.tsx
  src/components/XPubColumns/XPubsColumns.tsx
  src/components/ui/badge/badge.tsx
  src/components/ui/badge/badgeVariants.tsx
  src/components/ui/badge/index.ts
  src/components/ui/button/button.tsx
  src/components/ui/button/buttonVariants.tsx
  src/components/ui/button/index.ts
  src/components/ui/calendar.tsx
  src/components/ui/index.ts
  src/contexts/AuthContext/AuthContext.tsx
  src/contexts/AuthContext/index.ts
  src/contexts/AuthContext/types.ts
  src/contexts/AuthContext/useAuth.tsx
  src/contexts/AuthContext/useServerUrl.tsx
  src/contexts/SpvWalletContext/SpvWalletContext.tsx
  src/contexts/SpvWalletContext/index.ts
  src/contexts/SpvWalletContext/useSpvWalletClient.tsx
  src/contexts/ThemeProviderContext/ThemeProviderContext.tsx
  src/contexts/ThemeProviderContext/index.ts
  src/contexts/ThemeProviderContext/useTheme.tsx
  src/contexts/index.ts
  src/hooks/index.ts
  src/routes/admin/_admin.access-keys.tsx
  src/routes/admin/_admin.contacts.tsx
  src/routes/admin/_admin.destinations.tsx
  src/routes/admin/_admin.paymails.tsx
  src/routes/admin/_admin.transactions.tsx
  src/routes/admin/_admin.xpub.tsx
  src/routes/user/_user.access-keys.tsx
  src/routes/user/_user.destinations.tsx
  src/routes/user/_user.transactions.tsx
  src/searchSchemas/destinationSearchSchema.tsx
  src/searchSchemas/index.ts
  src/searchSchemas/transactionSearchSchema.tsx
  src/utils/createClient.ts
Labels: tested

#1000 feat(SPV-979): Added vitest, changed node version
  .github/workflows/on-push.yml
  package.json
  src/utils/getAddress.test.ts
  yarn.lock
Labels: tested

#1005 ci(SPV-992): use dependabot update groups
  .github/dependabot.yml
Labels: tested

#1007 feat(SPV-953): Change login page layout
  src/routes/login.tsx
Labels: tested

#985 feat(SPV-972): show deleted paymails
  src/utils/paymailsQueryOptions.tsx
Labels: tested

#1009 fix(SPV-997): console error when open access keys view
  src/components/AddAccessKeyDialog/AddAccessKeyDialog.tsx
Labels: tested

#1010 feat(SPV-XXX): Updated spv-wallet-js-client
  package.json
  yarn.lock
Labels: tested

#1011 Chore/spv 1003 curly brackets eslint
  eslint.config.js
  src/components/AddPaymailDialog/AddPaymailDialog.tsx
  src/components/AddXpubDialog/AddXpubDialog.tsx
  src/components/PaymailsColumns/PaymailColumns.tsx
  src/components/RecordTxDialogAdmin/RecordTxDialogAdmin.tsx
  src/contexts/ThemeProviderContext/useTheme.tsx
  src/routes/user/_user.xpub.tsx
Labels: tested

#1008 Feature/spv 988 prepare transactions improvements
  package.json
  src/components/RecordTxDialogUser/PrepareTxDialogUser.tsx
  src/components/ui/form/form-control.tsx
  src/components/ui/form/form-description.tsx
  src/components/ui/form/form-field-context.tsx
  src/components/ui/form/form-field.tsx
  src/components/ui/form/form-item-context.tsx
  src/components/ui/form/form-item.tsx
  src/components/ui/form/form-label.tsx
  src/components/ui/form/form-message.tsx
  src/components/ui/form/form.tsx
  src/components/ui/form/index.ts
  src/components/ui/form/use-form-field.tsx
  yarn.lock
Labels: tested

#988 feat(SPV-969): Added error handler component
  public/falling-man.png
  src/components/CustomErrorComponent/CustomErrorComponent.tsx
  src/components/CustomErrorComponent/index.ts
  src/components/index.ts
  src/routes/admin/_admin.access-keys.tsx
  src/routes/admin/_admin.contacts.tsx
  src/routes/admin/_admin.destinations.tsx
  src/routes/admin/_admin.paymails.tsx
  src/routes/admin/_admin.transactions.tsx
  src/routes/admin/_admin.xpub.tsx
  src/routes/user/_user.access-keys.tsx
  src/routes/user/_user.destinations.tsx
  src/routes/user/_user.transactions.tsx
  src/routes/user/_user.xpub.tsx
Labels: tested

#984 feat(SPV-971): Removed deleted tab, added option to add xpub directly
  package.json
  src/components/AddXpubDialog/AddXpubDialog.tsx
  src/routes/admin/_admin.xpub.tsx
  yarn.lock
Labels: tested

#989 feat(SPV-960): Replaced any with types
  src/components/AccessKeysTabContent/AccessKeysTabContent.tsx
  src/components/ContactAcceptDialog/ContactAcceptDialog.tsx
  src/components/ContactDeleteDialog/ContactDeleteDialog.tsx
  src/components/ContactEditDialog/ContactEditDialog.tsx
  src/components/ContactRejectDialog/ContactRejectDialog.tsx
  src/components/ContactsTabContent/ContactsTabContent.tsx
  src/components/DataTable/DataTable.tsx
  src/components/DestinationEditDialog/DestinationEditDialog.tsx
  src/components/DestinationsTabContent/DestinationsTabContent.tsx
  src/components/PaymailDeleteDialog/PaymailDeleteDialog.tsx
  src/components/PaymailsTabContent/PaymailsTabContent.tsx
  src/components/RecordTxDialogAdmin/RecordTxDialogAdmin.tsx
  src/components/RevokeKeyDialog/RevokeKeyDialog.tsx
  src/components/TransactionEditDialog/TransactionEditDialog.tsx
  src/components/TransactionsTabContent/TransactionsTabContent.tsx
  src/components/ViewDialog/ViewDialog.tsx
  src/logger/index.ts
  src/routes/admin/_admin.access-keys.tsx
  src/routes/admin/_admin.contacts.tsx
  src/routes/admin/_admin.paymails.tsx
  src/routes/admin/_admin.transactions.tsx
  src/routes/login.tsx
  src/routes/user/_user.access-keys.tsx
  src/routes/user/_user.destinations.tsx
  src/routes/user/_user.transactions.tsx
Labels: tested

#999 feat(SPV-955): Changed field type on login page
  src/components/ui/form/form.tsx
  src/components/ui/form/index.ts
  src/components/ui/index.ts
  src/routes/login.tsx
Labels: tested
