Repository bitcoin-sv/spv-wallet-admin, pull requests merged in 2025-02, with the labels that each got.

#1106 feat (SPV-1438) [spv-admin][user] Add the indicator that you are logged in as user
  src/contexts/SpvWalletContext/SpvWalletContext.tsx
  src/routes/user/_user.tsx
  src/utils/createClient.ts
Labels: tested

#1107 feat (SPV-1441) [spv-admin] Show dates converted to browser timezone and in localised way
  src/components/AccessKeysColumns/AccessKeysColumns.tsx
  src/components/ContactsColumns/ContactsColumns.tsx
  src/components/DateCell.tsx
  src/components/PaymailsColumns/PaymailColumns.tsx
  src/components/TransactionsColumns/columns.tsx
  src/components/ViewDialog/ViewDialog.tsx
  src/components/XPubColumns/XPubsColumns.tsx
  src/components/index.ts
Labels: tested

#1111 Deps/dependabot bump deps
  package.json
  src/components/PaymailsColumns/PaymailColumns.tsx
  src/index.css
  yarn.lock
Labels: tested

#1114 feat(SPV-1440): add dialog to inform user about new access key
  src/components/AddAccessKeyDialog/AddAccessKeyDialog.tsx
Labels: tested

#1113 Feat(spv 1493) update js client to a new version with split admin and user client
  package.json
  src/components/AddAccessKeyDialog/AddAccessKeyDialog.tsx
  src/components/AddPaymailDialog/AddPaymailDialog.tsx
  src/components/AddXpubDialog/AddXpubDialog.tsx
  src/components/ContactAcceptDialog/ContactAcceptDialog.tsx
  src/components/ContactDeleteDialog/ContactDeleteDialog.tsx
  src/components/ContactEditDialog/ContactEditDialog.tsx
  src/components/ContactRejectDialog/ContactRejectDialog.tsx
  src/components/PaymailDeleteDialog/PaymailDeleteDialog.tsx
  src/components/PaymailsTabContent/PaymailsTabContent.tsx
  src/components/Profile/Profile.tsx
  src/components/RecordTxDialogUser/PrepareTxDialogUser.tsx
  src/components/RevokeKeyDialog/RevokeKeyDialog.tsx
  src/components/TransactionEditDialog/TransactionEditDialog.tsx
  src/components/UnsubscribeWebhook/UnsubscribeWebhook.tsx
  src/components/UserBalance/UserBalance.tsx
  src/contexts/AuthContext/AuthProvider.tsx
  src/contexts/SpvWalletContext/SpvWalletContext.tsx
  src/contexts/SpvWalletContext/SpvWalletProvider.tsx
  src/routes/admin/_admin.access-keys.tsx
  src/routes/admin/_admin.contacts.tsx
  src/routes/admin/_admin.paymails.tsx
  src/routes/admin/_admin.transactions.tsx
  src/routes/admin/_admin.webhooks.tsx
  src/routes/admin/_admin.xpub.tsx
  src/routes/user/_user.access-keys.tsx
  src/routes/user/_user.paymails.tsx
  src/routes/user/_user.transactions.tsx
  src/routes/user/_user.tsx
  src/routes/user/_user.xpub.tsx
  src/store/clientStore.ts
  src/utils/accessKeysAdminQueryOptions.tsx
  src/utils/accessKeysQueryOptions.tsx
  src/utils/contactsQueryOptions.tsx
  src/utils/createClient.ts
  src/utils/paymailsAdminQueryOptions.tsx
  src/utils/paymailsQueryOptions.tsx
  src/utils/transactionsQueryOptions.tsx
  src/utils/transactionsUserQueryOptions.tsx
  src/utils/userBalanceQueryOptions.tsx
  src/utils/webhooksQueryOptions.tsx
  src/utils/xPubQueryOptions.tsx
  yarn.lock
Labels: feature, tested

#1117 Bug(SPV-1443) [spv-admin][transactions] invalid statuses are displayed
  src/components/TransactionsColumns/columns.tsx
  src/components/ui/index.ts
  src/components/ui/transaction-status-badge.tsx
Labels: tested

#1116 task(SPV-1449) [spv-admin][admin] remove filter by balance on xpubs
  package.json
  src/components/AddAccessKeyDialog/AddAccessKeyDialog.tsx
  src/components/AddPaymailDialog/AddPaymailDialog.tsx
  src/components/AddXpubDialog/AddXpubDialog.tsx
  src/components/ContactAcceptDialog/ContactAcceptDialog.tsx
  src/components/ContactDeleteDialog/ContactDeleteDialog.tsx
  src/components/ContactEditDialog/ContactEditDialog.tsx
  src/components/ContactRejectDialog/ContactRejectDialog.tsx
  src/components/PaymailDeleteDialog/PaymailDeleteDialog.tsx
  src/components/PaymailsTabContent/PaymailsTabContent.tsx
  src/components/Profile/Profile.tsx
  src/components/RecordTxDialogUser/PrepareTxDialogUser.tsx
  src/components/RevokeKeyDialog/RevokeKeyDialog.tsx
  src/components/TransactionEditDialog/TransactionEditDialog.tsx
  src/components/TransactionsColumns/columns.tsx
  src/components/UnsubscribeWebhook/UnsubscribeWebhook.tsx
  src/components/UserBalance/UserBalance.tsx
  src/components/ui/index.ts
  src/components/ui/transaction-status-badge.tsx
  src/contexts/AuthContext/AuthProvider.tsx
  src/contexts/SpvWalletContext/SpvWalletContext.tsx
  src/contexts/SpvWalletContext/SpvWalletProvider.tsx
  src/routes/admin/_admin.access-keys.tsx
  src/routes/admin/_admin.contacts.tsx
  src/routes/admin/_admin.paymails.tsx
  src/routes/admin/_admin.transactions.tsx
  src/routes/admin/_admin.webhooks.tsx
  src/routes/admin/_admin.xpub.tsx
  src/routes/user/_user.access-keys.tsx
  src/routes/user/_user.paymails.tsx
  src/routes/user/_user.transactions.tsx
  src/routes/user/_user.tsx
  src/routes/user/_user.xpub.tsx
  src/store/clientStore.ts
  src/utils/accessKeysAdminQueryOptions.tsx
  src/utils/accessKeysQueryOptions.tsx
  src/utils/contactsQueryOptions.tsx
  src/utils/createClient.ts
  src/utils/index.ts
  src/utils/paymailsAdminQueryOptions.tsx
  src/utils/paymailsQueryOptions.tsx
  src/utils/prepareXPubFilters.ts
  src/utils/transactionsQueryOptions.tsx
  src/utils/transactionsUserQueryOptions.tsx
  src/utils/userBalanceQueryOptions.tsx
  src/utils/webhooksQueryOptions.tsx
  src/utils/xPubQueryOptions.tsx
  yarn.lock
Labels: automerge, tested

#1121 Feat(spv 1493) update js client to a new version with split admin and user client
  package.json
  src/components/AddAccessKeyDialog/AddAccessKeyDialog.tsx
  src/components/AddPaymailDialog/AddPaymailDialog.tsx
  src/components/AddXpubDialog/AddXpubDialog.tsx
  src/components/ContactAcceptDialog/ContactAcceptDialog.tsx
  src/components/ContactDeleteDialog/ContactDeleteDialog.tsx
  src/components/ContactEditDialog/ContactEditDialog.tsx
  src/components/ContactRejectDialog/ContactRejectDialog.tsx
  src/components/PaymailDeleteDialog/PaymailDeleteDialog.tsx
  src/components/PaymailsTabContent/PaymailsTabContent.tsx
  src/components/Profile/Profile.tsx
  src/components/RecordTxDialogUser/PrepareTxDialogUser.tsx
  src/components/RevokeKeyDialog/RevokeKeyDialog.tsx
  src/components/TransactionEditDialog/TransactionEditDialog.tsx
  src/components/UnsubscribeWebhook/UnsubscribeWebhook.tsx
  src/components/UserBalance/UserBalance.tsx
  src/contexts/AuthContext/AuthProvider.tsx
  src/contexts/SpvWalletContext/SpvWalletContext.tsx
  src/contexts/SpvWalletContext/SpvWalletProvider.tsx
  src/routes/admin/_admin.access-keys.tsx
  src/routes/admin/_admin.contacts.tsx
  src/routes/admin/_admin.paymails.tsx
  src/routes/admin/_admin.transactions.tsx
  src/routes/admin/_admin.webhooks.tsx
  src/routes/admin/_admin.xpub.tsx
  src/routes/user/_user.access-keys.tsx
  src/routes/user/_user.paymails.tsx
  src/routes/user/_user.transactions.tsx
  src/routes/user/_user.tsx
  src/routes/user/_user.xpub.tsx
  src/store/clientStore.ts
  src/utils/accessKeysAdminQueryOptions.tsx
  src/utils/accessKeysQueryOptions.tsx
  src/utils/contactsQueryOptions.tsx
  src/utils/createClient.ts
  src/utils/paymailsAdminQueryOptions.tsx
  src/utils/paymailsQueryOptions.tsx
  src/utils/transactionsQueryOptions.tsx
  src/utils/transactionsUserQueryOptions.tsx
  src/utils/userBalanceQueryOptions.tsx
  src/utils/webhooksQueryOptions.tsx
  src/utils/xPubQueryOptions.tsx
  yarn.lock
Labels: tested

#1115 feat(SPV-1506) Update styling on mobile devices
  src/components/Profile/Profile.tsx
  src/routes/admin/_admin.tsx
  src/routes/login.tsx
  src/routes/user/_user.tsx
  src/routes/user/_user.xpub.tsx
  src/store/clientStore.ts
Labels: tested
